plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.146'
}

version = '1.0.0'
group = 'com.neryos.goatapples'

base {
    archivesName = 'goatapples-neoforge-1.21.1'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.249'

    parchment {
        mappingsVersion = '2024.11.17'
        minecraftVersion = '1.21.1'
    }

    mods {
        'goatapples' {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run')
        }
        server {
            server()
            gameDirectory = project.file('run/server')
            programArgument '--nogui'
        }

        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
